# SQLite configuration for development and test environments
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

# PostgreSQL configuration for production (adjust as needed)
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: your_database_name
  username: your_database_user
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
